### ISSUE TITLE
这种垃圾项目赶紧关了吧 ，别占用GITHUB资源了

### ISSUE THREAD

**Issue by zhaokaixs** [tsingsee/EasyPlayerPro-Win#23]
卖授权你就好好在自己网站上卖

**Comment by raidenzxx** [comment]
你就老老实实用ffmpeg吧，这个只能看看
from 阿里邮箱 iPad------------------------------------------------------------------
***@***.***>
日　期：2023年05月26日 16:48:50
***@***.***>
***@***.***>
主　题：[tsingsee/EasyPlayerPro-Win] 这种垃圾项目赶紧关了吧 ，别占用GITHUB资源了 (Issue #23)

卖授权你就好好在自己网站上卖
